title: "Pina Image"
email: "&#x69;&#x6F;&#x6E;&#x75;&#x74;&#x70;&#x69;&#x6E;&#x74;&#x65;&#x61;&#x32;&#x35;&#x40;&#x67;&#x6D;&#x61;&#x69;&#x6C;&#x2E;&#x63;&#x6F;&#x6D;" #https://mothereff.in/html-entities
phone: "0744422250"
author: "Simion Ionuţ Pîntea"
description: >- 
  Fotograf

baseurl: ""
url: "https://pinaimage.ro/"

header-links:
  instagram: "pina.image"
  facebook: "pina.image"

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

collections:
  events:
    output: true
    permalink: /:collection/:path

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
